sonar.projectKey=rekr-app

sonar.sources=backend/src,clientApp/src

sonar.tests=backend/src,clientApp/src
sonar.test.inclusions=**/*.spec.ts,**/*.spec.tsx,**/*.test.ts,**/*.test.tsx

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/generated/**,**/coverage/**,**/*.config.ts,**/*.config.js,**/*.config.mjs

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,clientApp/coverage/lcov.info
